### ISSUE TITLE
No Default Metadata

### ISSUE THREAD

**Issue by Nickyfan7** [darklinkpower/Harmony#1]
When using Harmony and setting a default picture for Cover Images they don't display properly as some games will display it and other will not simply using the Playnite default grid image.

**To Reproduce**
I had simply setup base covers to use (some of which I made myself) and changed the settings to use the preset ones instead of the base playnite ones, the result was that it only worked on one game: Sonic the Hedgehog 2 for the Sega Genesis however I already had a grid prepared for that game.

All of my other games (mainly mods) didn't adopt the preset cover however even after resetting playnite:
[Harmony Grids](https://i.imgur.com/mzNQCFh.png)

Upon switching back to the base theme however the default console-based grids worked:
[Harmony Grids](https://i.imgur.com/DLFsx6Y.png)

So I can only suspect that it's harmony possibly not drawing/rendering them correctly that causes it plus this may just be a hunch but I believe that it won't likely display the other metadata (Background Image/ Icons) I haven't tried it so I can't say for certain but it's possible.

**Comment by darklinkpower** [comment]
Fixed
