### ISSUE TITLE
Game Tile in Grid Mode doesn't darken after uninstalling

### ISSUE THREAD

**Issue by PrivacyFriendlyMuffins** [darklinkpower/Harmony#15]
### Bug Description

**Conditions**: Under Settings > Appearance > Grid View, check "Darken not installed games".

**Expected Behavior**: The tile for a any uninstalled game would darken.

**Actual Behavior**: The tiles for all uninstalled games remains the same brightness, saturation, etc. as any installed games.

---
**Specs**

- Operating System: Windows 10
- Playnite Version: 10.2
- Harmony Version: 2.34

---
### To Reproduce

1. Go to Settings > Appearance > Grid View and check "Darken not installed games".
2. Look at the tiles for any game(s) displayed that is not currently installed.

### Screenshots

![Harmony Bug](https://user-images.githubusercontent.com/86497467/192167153-dc968502-cde3-4690-bcd3-0ab0b1b62f34.png)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/Harmony/commit/af45798bcdb6e5d65a3e2121f4a8c05a54e052d9 and available in v2.35 update
