### ISSUE TITLE
Wide search view aligns right by default

### ISSUE THREAD

**Issue by Jeshibu** [darklinkpower/Harmony#18]
### Bug Description

If the search results (ctrl+F) are wider than the view, the view shows the rightmost side, leaving most game data out of view.

### To Reproduce

Give a game a whole lot of platforms
Press CTRL+F
Bring it up in the search results

### Screenshots

![image](https://user-images.githubusercontent.com/37979717/199324395-787234ee-748a-4418-b9fe-30fc2661e56f.png)

**Comment by darklinkpower** [comment]
Fixed
