### ISSUE TITLE
Low/no contrast button text

### ISSUE THREAD

**Issue by Jeshibu** [darklinkpower/Harmony#22]
### Bug Description

Overall the overhaul has been positive, but there's a few buttons that don't have enough contrast in their text:
- When you open the game edit window and click `Download metadata` and then a provider, the button gets set to a low-contrast version - when clicked again it flips back to the normal colors
![image](https://github.com/darklinkpower/Harmony/assets/37979717/f8e55796-7fe9-47e8-9458-694b3c28d533)
- The detail view play button normally is good: 
![image](https://github.com/darklinkpower/Harmony/assets/37979717/ec6c8f36-3a66-46b5-8f8a-6343541abf0b)
- When hovered however, the text is the same color as the background
![image](https://github.com/darklinkpower/Harmony/assets/37979717/066762dc-e87a-4c9b-85f7-c8911718acbf)

**Comment by darklinkpower** [comment]
Fixed in new update
