### ISSUE TITLE
No longer possible to disable side bar

### ISSUE THREAD

**Issue by poudi7** [darklinkpower/Harmony#23]
### Bug Description

Since the last release, it is no longer possible to disable the sidebar. The icon disappears, but the bar remains.

Windows 11
Playnite 10.19
Harmony v2.49

### Screenshots

![Screenshot 2023-10-12 051527](https://github.com/darklinkpower/Harmony/assets/3994455/b5a9bd5f-c933-47e9-b4e1-f84ea17b3e3c)
![Screenshot 2023-10-12 052351](https://github.com/darklinkpower/Harmony/assets/3994455/c658ccfd-106b-4ebf-b0b9-11706cbbfe08)

**Comment by darklinkpower** [comment]
Fixed in new update
