### ISSUE TITLE
[Feature Request] ThemeModifier option to center covers

### ISSUE THREAD

**Issue by ferrazpedro** [darklinkpower/Harmony#3]
### Bug Description

I don't know if this was a deliberate choice, but since the last release all game covers aren't centered anymore.

### Screenshots

![image](https://user-images.githubusercontent.com/37643357/165526732-e17f350b-8932-42a1-9f3d-260fe18115a8.png)

**Comment by darklinkpower** [comment]
This change was made along with the new library banners feature in the new version. Personally I think it looks better this way, what do you think? My reasoning is that it looks very weird and inconsistent when games have covers with different sizes and aspect ratios. This way it looks much more uniform and consistent.

**Comment by ferrazpedro** [comment]
Thanks for the quick response! Well, I do believe that centered covers looks cleaner but I do undestand that this is totally subjective. Since this wasn't a bug, I'm closing this issue. Thanks a lot for all the hard work, btw!

**Comment by ferrazpedro** [comment]
Hey! I know I've closed this issue before, when I thought it was a bug, but I've realized that this would be a great option if doable. I do think this is the best Playnite theme that exists right now and these covers are the only dealbreaker that i'm struggling with...
