### ISSUE TITLE
Riot Games not detected for Library Banners

### ISSUE THREAD

**Issue by Dobbi124** [darklinkpower/Harmony#33]
### Bug Description

Riot Games library games not detected for the library banner 

![Screenshot 2024-11-11 170234](https://github.com/user-attachments/assets/102c3b16-f0ee-4f90-9804-b3859db34cfc)

### To Reproduce

Install a Riot Game
Enable the Option to allow Banners

**Comment by darklinkpower** [comment]
Was that game added manually or by the library plugin? Currently only the plugin banner is available.

**Comment by darklinkpower** [comment]
Banner available in new update.
