### ISSUE TITLE
Add platform banner to cover without covering art

### ISSUE THREAD

**Issue by Smumbo** [darklinkpower/Harmony#4]
### Feature Description

I'm wondering if it's possible to "prepend" the newly added platform banners to the game covers in grid view. By "prepend" I just mean adding the banner to the cover without it covering the artwork (so basically appending it to the top).

I've attached an example of how I imagine this would look. This mockup also includes the platform icons from DuplicateHider and the Favorite icon included on the cover just to further illustrate how this enhancement would assist with visibility and UI functionality.

If this is not the appropriate place to suggest this improvement, please let me know where I should send this feedback.

### Screenshots

Before:
![Before](https://user-images.githubusercontent.com/38147112/165637392-6a5b96cf-ab40-4fc3-bb81-d0d32b624c0d.png)

After:
![After](https://user-images.githubusercontent.com/38147112/165637400-3824c78d-65d7-4a81-963c-5da71597c28d.png)

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Harmony/commit/c057ba32df44a7daa2cd127833c455e1f4ce2c97

**Comment by darklinkpower** [comment]
I didn't look into changing the icons of duplicate hider and favorites, for that please open a new issue.

**Comment by Smumbo** [comment]
Thanks! This issue isn't related to those icons, I was just pointing out that I included them in the mockup for illustration purposes.
