### ISSUE TITLE
Grid view detail panel has too much margin

### ISSUE THREAD

**Issue by Jeshibu** [darklinkpower/Harmony#9]
### Bug Description

The grid view detail panel (when switched via your Grid View Converter at least) has a margin greater than the panel(s) next to it, making it smaller than necessary.

### To Reproduce

Enable `Settings > Appearance > Layout > Draw separator between panels`

### Screenshots

![image](https://user-images.githubusercontent.com/37979717/188740980-b5d06e8d-d51e-470f-92d1-8f01e71f25c9.png)

**Comment by Jeshibu** [comment]
This might actually be an issue with the grid view details extension.

**Comment by darklinkpower** [comment]
Fixed

**Comment by rattailgamer** [comment]
> Fixed

The issue is back :(
